---
title: "Basic stats sgRNA library"
author: "Author: Stefanus Bernard"
date: "Date: `r format(Sys.time(), '%d %B %Y')`"
output: 
    html_document:
      theme: cerulean
      toc: true
      toc_float: true
      number_sections: true
      self_contained: true
---

```{r}
library(tidyverse)
library(readxl)
library(VennDiagram)
library(grid)
library(paletteer)
library(RColorBrewer)
source('../CRISPR-KO-library-refinement-pipeline/sgRNA_library_refinement_pipeline_functions.R')
```

# Import the data of sgRNA library report

```{r}
brunello <- 'broadgpp-brunello-library-contents'
toronto <- 'tkov3_guide_sequence'
avana <- 'avana_library'
yusa <- 'yusa_hcrispr_ko_grnas'

brunello_report <- read_excel(paste('../CRISPR-KO-library-refinement-pipeline/output_cleaning/hg38/', brunello, '_full_report.xlsx', sep = ''))
toronto_report <- read_excel(paste('../CRISPR-KO-library-refinement-pipeline/output_cleaning/hg38/', toronto, '_full_report.xlsx', sep = ''))
avana_report <- read_excel(paste('../CRISPR-KO-library-refinement-pipeline/output_cleaning/hg38/', avana, '_full_report.xlsx', sep = ''))
yusa_report <- read_excel(paste('../CRISPR-KO-library-refinement-pipeline/output_cleaning/hg38/', yusa, '_full_report.xlsx', sep = ''))

```

# Calculate the percentage of multi-target, single-mismatch, and PAM-distal double mismatch sgRNA in each libraries

```{r}

calculate_percentage <- function(library_report, discarded_sgrna, original_sgrna) {
    percentage_discarded <- (sum(library_report[[discarded_sgrna]])/sum(library_report[[original_sgrna]])) * 100
    return(percentage_discarded)
}

brunello_multi_target <- round(calculate_percentage(brunello_report, "multi-target sgRNA", "sgRNA number"), 2)
toronto_multi_target <- round(calculate_percentage(toronto_report, "multi-target sgRNA", "sgRNA number"), 2)
avana_multi_target <- round(calculate_percentage(avana_report, "multi-target sgRNA", "sgRNA number"), 2)
yusa_multi_target <- round(calculate_percentage(yusa_report, "multi-target sgRNA", "sgRNA number"), 2)

brunello_single_mismatch <- round(calculate_percentage(brunello_report, "single mismatch sgRNA", "sgRNA number"), 2)
toronto_single_mismatch <- round(calculate_percentage(toronto_report, "single mismatch sgRNA", "sgRNA number"), 2)
avana_single_mismatch <- round(calculate_percentage(avana_report, "single mismatch sgRNA", "sgRNA number"), 2)
yusa_single_mismatch <- round(calculate_percentage(yusa_report, "single mismatch sgRNA", "sgRNA number"), 2)

brunello_pam_distal <- round(calculate_percentage(brunello_report, "PAM distal double mismatch", "sgRNA number"), 2)
toronto_pam_distal <- round(calculate_percentage(toronto_report, "PAM distal double mismatch", "sgRNA number"), 2)
avana_pam_distal <- round(calculate_percentage(avana_report, "PAM distal double mismatch", "sgRNA number"), 2)
yusa_pam_distal <- round(calculate_percentage(yusa_report, "PAM distal double mismatch", "sgRNA number"), 2)


# Create dataframe for multi-target, single-mismatch, and pam-distal from all library

multi_target <- c(brunello_multi_target, toronto_multi_target, yusa_multi_target, avana_multi_target)
single_mismatch <- c(brunello_single_mismatch, toronto_single_mismatch, yusa_single_mismatch, avana_single_mismatch)
pam_distal <- c(brunello_pam_distal, toronto_pam_distal, yusa_pam_distal, avana_pam_distal)

library <- c("brunello", "toronto_v3", "yusa", "avana")
factor <- c(1,2,3,4)

sum_dataframe <- data.frame(library, multi_target, single_mismatch, pam_distal)


# Histogram of multi-target/off-target sgRNAs in Cellecta, Brunello, and Toronto
# Reorder the library factor to ensure the bars are ordered as Brunello, Toronto, Yusa, Avana
sum_dataframe_long <- sum_dataframe %>%
    pivot_longer(cols = c("multi_target", "single_mismatch", "pam_distal"), 
                 names_to = "category", 
                 values_to = "percentage") %>%
    mutate(category = factor(category, levels = c("multi_target", "single_mismatch", "pam_distal")),
           library = factor(library, levels = c("brunello", "toronto_v3", "yusa", "avana")))


# Define custom colors for the libraries
my_palette <- brewer.pal(n = 4, name = "Set2")


# Create the grouped multibar chart for each sgRNA libraries
multi_bar_chart <- ggplot(sum_dataframe_long, aes(x = category, y = percentage, fill = library)) +
    geom_bar(stat = "identity", position = position_dodge2(padding = 0.2), width = 0.7) +
    theme_minimal() +
    labs(title = "", x = "", y = "sgRNA (%)") +
    scale_x_discrete(labels = c('multi_target' = 'Multi-target sgRNA',
                                'single_mismatch' = 'Single mismatch sgRNA',
                                'pam_distal' = 'PAM distal \n double mismatch sgRNA')) +
    geom_text(aes(label = paste(percentage, "%", sep = '')), position = position_dodge2(width = 0.7), vjust = -0.5, size = 9) +
    theme(axis.text.x = element_text(size = 40, vjust = 0.7, colour = 'black'),
          axis.text.y = element_text(size = 40),
          axis.title.y = element_text(size = 40, vjust = 0.5, margin = margin(r = 20)),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line.x = element_line(size = 0.5),
          axis.line.y = element_line(size = 0.5),
          legend.title = element_text(size = 40),
          legend.text = element_text(size = 40),
          plot.margin = margin(1, 1, 1, 1), 
          line = element_line((size = 4), colour = 'black'),
          legend.spacing.x = unit(1, 'cm')) +
    scale_fill_manual(values = my_palette,
                      name = 'Library',
                      breaks = c("brunello", "toronto_v3", "yusa", "avana"),
                      labels = c("brunello" = "Brunello",
                                 "toronto_v3" = "Toronto Knockout V3",
                                 "yusa" = "Yusa Project Score",
                                 "avana" = "Avana")) + 
  scale_y_continuous(breaks=seq(0, 10, 2), limits=c(0, 10))

multi_bar_chart

ggsave(
    path = './',
    width = 30,
    height = 15,
    dpi = 300,
    plot = multi_bar_chart,
    filename = paste('./plot/percentage_off_target.png', sep = ''))
```

# Percentage of sgRNAs not represented after library refinement
# Percentage of genes not represented after library refinement

```{r}

import_library <- function(lib_dir){
  library <- read_tsv(lib_dir, col_names = FALSE)
  colnames(library) <- c("sgrna", "spacer", "gene")
  
  return(library)
}

brunello_library <- import_library("../CRISPR-KO-library-refinement-pipeline/public_crispr_library/broadgpp-brunello-library-contents.tsv")
toronto_library <- import_library("../CRISPR-KO-library-refinement-pipeline/public_crispr_library/tkov3_guide_sequence.tsv")
avana_library <- import_library("../CRISPR-KO-library-refinement-pipeline/public_crispr_library/avana_library.tsv")
yusa_library <- import_library("../CRISPR-KO-library-refinement-pipeline/public_crispr_library/yusa_hcrispr_ko_grnas.tsv")

brunello_refined <- import_library("../CRISPR-KO-library-refinement-pipeline/output_cleaning/hg38/broadgpp-brunello-library-contents_65K_refined.tsv")
toronto_refined <- import_library("../CRISPR-KO-library-refinement-pipeline/output_cleaning/hg38/tkov3_guide_sequence_62K_refined.tsv")
avana_refined <- import_library("../CRISPR-KO-library-refinement-pipeline/output_cleaning/hg38/avana_library_56K_refined.tsv")
yusa_refined <- import_library("../CRISPR-KO-library-refinement-pipeline/output_cleaning/hg38/yusa_hcrispr_ko_grnas_76K_refined.tsv")

round(length(unique(brunello_refined$sgrna)))
round(length(unique(brunello_library$sgrna)))

percentage_brunello <- round(100 - round(length(unique(brunello_refined$gene)) / length(unique(brunello_library$gene)) * 100, 2), 2)
percentage_toronto <- round(100 - round(length(unique(toronto_refined$gene)) / length(unique(toronto_library$gene)) * 100, 2), 2)
percentage_avana <- round(100 - round(length(unique(avana_refined$gene)) / length(unique(avana_library$gene)) * 100, 2), 2)
percentage_yusa <- round(100 - round(length(unique(yusa_refined$gene)) / length(unique(yusa_library$gene)) * 100, 2), 2)

df_percentage <- data.frame(library = c("brunello", "toronto_v3", "yusa", "avana"),
                            percentage_genes = c(percentage_brunello, percentage_toronto, percentage_yusa, percentage_avana))

df_percentage <- df_percentage %>%
  mutate(library = factor(library, levels = c("brunello", "toronto_v3", "yusa", "avana")))


```
# Plot of sgRNAs and genes that are not represented in the refined library

```{r}

my_palette <- brewer.pal(n = 4, name = "Set2")

percentage_bar_chart <- ggplot(df_percentage, aes(x = library, y = percentage_genes, fill = library)) +
    geom_bar(stat = "identity", position = position_dodge2(padding = 0.2), width = 0.7) +
    theme_minimal() +
    labs(title = "", x = "", y = "Genes targeted by < 3 sgRNAs (%)") +
    scale_x_discrete(labels = c("brunello" = "Brunello",
                                 "toronto_v3" = "Toronto \nKnockout V3",
                                 "yusa" = "Yusa \nProject Score",
                                 "avana" = "Avana")) +
    geom_text(aes(label = paste(percentage_genes, "%", sep = '')), position = position_dodge2(width = 0.7), vjust = -0.5, size = 12) +
    theme(axis.text.x = element_text(size = 40, vjust = 0.7, colour = 'black'),
          axis.text.y = element_text(size = 40),
          axis.title.y = element_text(size = 40, vjust = 0.5, margin = margin(r = 20)),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line.x = element_line(size = 0.5),
          axis.line.y = element_line(size = 0.5),
          legend.title = element_text(size = 40),
          legend.text = element_text(size = 40),
          plot.margin = margin(1, 1, 1, 1), 
          line = element_line((size = 4), colour = 'black'),
          legend.spacing.x = unit(1, 'cm')) +
    scale_fill_manual(values = my_palette,
                      name = 'Library',
                      breaks = c("brunello", "toronto_v3", "yusa", "avana"),
                      labels = c("brunello" = "Brunello",
                                 "toronto_v3" = "Toronto Knockout V3",
                                 "yusa" = "Yusa Project Score",
                                 "avana" = "Avana")) +
    ylim(0, 100)

percentage_bar_chart

ggsave(
    path = './',
    width = 25,
    height = 15,
    dpi = 300,
    plot = percentage_bar_chart,
    filename = paste('./plot/library_genes_bar_chart.png', sep = ''))

```

