---
title: "Analysis of Brunello and Jacquere A375 cells hits"
author: "Author: Stefanus Bernard"
date: "Date: `r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document :
    theme : cerulean
    toc : true
    toc_float : true
    number_section : true
---

# Import packages

```{r}
library(MAGeCKFlute)
library(tidyverse)
library(ggrepel)
library(ggExtra)
library(hgnc)
library(HGNChelper)
library(purrr)
library(xlsx)
library(readxl)
library(pheatmap)
library(stringr)
library(ggpubr)
source("../00_CRISPR-KO-library-survey-functions.R")
```

# Important function

```{r}

CallMAGeCKHits <- function(gene_summary, scale = 2, beta_colnames) {

  # 1. Mean beta across replicates
  gene_summary$Diff <- rowMeans(
    gene_summary[, beta_colnames]
  )

  # 2. SD-based cutoff
  cc <- CutoffCalling(gene_summary$Diff, scale = scale)

  # 3. Initial classification
  gene_summary$hits_classification <- "Neutral"
  gene_summary$hits_classification[gene_summary$Diff <= -cc] <- "Essential genes"
  gene_summary$hits_classification[gene_summary$Diff >= cc] <- "Growth suppressor genes"

  # 4. Enforce replicate consistency
  gene_summary$hits_classification[
    gene_summary$hits_classification == "Essential genes" &
      !(gene_summary$repA < 0 & gene_summary$repB < 0)
  ] <- "Neutral"

  gene_summary$hits_classification[
    gene_summary$hits_classification == "Growth suppressor genes" &
      !(gene_summary$repA > 0 & gene_summary$repB > 0)
  ] <- "Neutral"

  return(gene_summary)
}


```

# Import MAGeCK MLE gene summary result

```{r}

brunello_original <- read_tsv("../../data/read_count_data/A375_brunello_original/A375_brunello_original.gene_summary.txt")
brunello_refined <- read_tsv("../../data/read_count_data/A375_brunello_refined/A375_brunello_refined.gene_summary.txt")

jacquere_original <- read_tsv("../../data/read_count_data/A375_jacquere_original/A375_jacquere_original.gene_summary.txt")
jacquere_refined <- read_tsv("../../data/read_count_data/A375_jacquere_refined/A375_jacquere_63K_refined.gene_summary.txt")

```

# Find hits

```{r}
brunello_original_hits <- CallMAGeCKHits(brunello_original, scale = 2, beta_colnames = c("RepA|beta", "RepB|beta", "RepC|beta"))
brunello_original_hits <- brunello_original_hits %>%
  filter(`RepA|wald-fdr` <= 0.05 & `RepB|wald-fdr` <= 0.05 & `RepC|wald-fdr` <= 0.05)

brunello_refined_hits <- CallMAGeCKHits(brunello_refined, scale = 2, beta_colnames = c("RepA|beta", "RepB|beta", "RepC|beta"))
brunello_refined_hits <- brunello_refined_hits %>%
  filter(`RepA|wald-fdr` <= 0.05 & `RepB|wald-fdr` <= 0.05 & `RepC|wald-fdr` <= 0.05)

jacquere_original_hits <- CallMAGeCKHits(jacquere_original, scale = 2, beta_colnames = c("A375_CP0082_repA|beta", "A375_CP0082_repB|beta"))
jacquere_original_hits <- jacquere_original_hits %>%
  filter(`A375_CP0082_repA|wald-fdr` <= 0.05 & `A375_CP0082_repB|wald-fdr` <= 0.05)

jacquere_refined_hits <- CallMAGeCKHits(jacquere_refined, scale = 2, beta_colnames = c("A375_CP0082_repA|beta", "A375_CP0082_repB|beta"))
jacquere_refined_hits <- jacquere_refined_hits %>%
  filter(`A375_CP0082_repA|wald-fdr` <= 0.05 & `A375_CP0082_repB|wald-fdr` <= 0.05)

```

# Pull hits

```{r}

brunello_original_hits_list <- fix_gene_symbols(brunello_original_hits$Gene) %>% pull(Suggested.Symbol) %>% unique()
brunello_refined_hits_list <- fix_gene_symbols(brunello_refined_hits$Gene) %>% pull(Suggested.Symbol) %>% unique()

brunello_original_only_hits <- setdiff(brunello_original_hits_list, brunello_refined_hits_list)


jacquere_original_hits_list <- fix_gene_symbols(jacquere_original_hits$Gene) %>% pull(Suggested.Symbol) %>% unique()
jacquere_refined_hits_list <- jacquere_refined_hits %>% pull(Gene)

jacquere_original_only_hits <- setdiff(jacquere_original_hits_list, jacquere_refined_hits_list)

combined_vecs <- list(brunello_original_hits = brunello_original_hits_list,
                         brunello_refined_hits = brunello_refined_hits_list,
                         jacquere_original_hits = jacquere_original_hits_list,
                         jacquere_refined_hits = jacquere_refined_hits_list)

max_len <- max(lengths(combined_vecs))


final_df <- as.data.frame(
lapply(combined_vecs, function(x) {
length(x) <- max_len
x
})
)

write_csv(final_df, "../../data/result_gene_hits_change/brunello_jacquere_A375_hits_change.tsv")

```

## Survey of multi-targeting and off-targeting guides in Brunello and Jacquere

### Isolate CRISPR-KO screens that used A375 cells from DepMap

```{r}

model_data <- read_csv("../../data/hits_change_data/Model_25Q3_03022025.csv") %>%
  filter(str_detect(CellLineName, "A375|A-375")) %>%
  select(ModelID, CellLineName)

gene_effect <- read_csv("../../data/hits_change_data/CRISPRGeneEffect_25Q3_03022025.csv") %>%
  dplyr::rename("sample" = `...1`) %>%
  rename_with(~ str_remove(.x, "\\s*\\(\\d+\\)")) %>%
  filter(sample %in% model_data$ModelID) %>%
  as.matrix() %>%
  t() %>%
  as.data.frame() %>%
  drop_na()

first_row <- as.character(unlist(gene_effect[1, , drop = FALSE]))
colnames(gene_effect) <- first_row
gene_effect <- gene_effect[-1, ] %>%
   mutate(across(everything(), as.numeric))

# Use this if you want ACH-000219 cells only

A375_essential <- gene_effect %>%
  rownames_to_column("gene") %>%
  select(gene, `ACH-000219`) %>%
  filter(`ACH-000219` < -0.5)

# Use this if you want the median of all A375 cells

# gene_effect_median <- gene_effect %>%
#   mutate(across(c("ACH-000219", "ACH-002001", "ACH-002002", "ACH-002003"), as.numeric)) %>%
#   drop_na() %>%
#   mutate(
#     median_effect = apply(
#       select(., `ACH-000219`, `ACH-002001`, `ACH-002002`, `ACH-002003`),
#       1,
#       median,
#       na.rm = TRUE
#     )
#   )

# A375_essential <- gene_effect_median %>%
#   rownames_to_column("gene") %>%
#   filter(median_effect < -0.5)

```

### Brunello analysis

```{r}
pick_alignment_type <- function(classification_data, alignment_type, stratification_data) {
  data <- read_csv(classification_data) %>%
    filter(alignment %in% alignment_type)
  
  return(data)
}

selected_guides <- c("perfect", "single mismatch", "pam-distal double mismatch", "multi-target guides", "non-targeting")

brunello_classification <- pick_alignment_type("../../data/sgrna_lfc_data/brunello_data/brunello_sgrna_alignment_classification.csv", selected_guides)
brunello_classification <- count_alignment_bin(brunello_classification, selected_guides)

# depmap_common_essential <- read_csv("../../data/CRISPRInferredCommonEssentials.csv") %>%
#   mutate(Essentials = str_remove(Essentials, "\\s*\\(.*\\)")) %>%
#   pull(Essentials)

brunello_essentiality_profiles <- brunello_original_hits %>%
  select(Gene, Diff, hits_classification) %>%
  dplyr::rename("gene" = "Gene")

brunello_original_only_hits_analysis <- brunello_classification[[1]] %>%
  filter(gene %in% brunello_original_only_hits) %>%
  left_join(brunello_essentiality_profiles, join_by(gene)) %>%
  mutate(is_depmap_essential = ifelse(gene %in% A375_essential$gene, TRUE, FALSE))

setdiff(brunello_original_only_hits, brunello_original_only_hits_analysis$gene)

not_essential_but_hits_brunello <- brunello_original_only_hits_analysis %>%
  select(-spacer) %>%
  filter(is_depmap_essential == FALSE)

essential_and_hits_brunello <- brunello_original_only_hits_analysis %>%
  select(-spacer) %>%
  filter(is_depmap_essential == TRUE)

survey <- brunello_original_only_hits_analysis %>%
  select(gene, alignment, alignment_bin, Diff) %>%
  group_by(gene) %>%
  count(alignment, alignment_bin) %>%
  dplyr::rename("num_guides" = "n")  %>%
  mutate(is_depmap_essential = ifelse(gene %in% A375_essential$gene, TRUE, FALSE)) %>%
  ungroup(gene)

survey %>%
  select(gene, is_depmap_essential) %>%
  distinct() %>%
  count(is_depmap_essential) %>%
  dplyr::rename("num_genes" = "n") %>%
  ggplot(aes(is_depmap_essential, num_genes)) +
     geom_col(fill = "#1E88E5") +
     theme_minimal() +
     labs(x = "A375 essential genes", y = "Number of gene hits") +
     geom_text(aes(label = paste("n= ", num_genes, sep="")),
                nudge_y = 10,
                nudge_x = 0,
                size = 8) +
  theme(axis.text.x = element_text(size = 25, vjust = 0.7, colour = 'black'),
          axis.text.y = element_text(size = 25, colour = "black"),
          axis.title.x = element_text(size = 25, vjust = 0.5, margin = margin(t = 20), colour = "black"),
          axis.title.y = element_text(size = 25, vjust = 0.5, margin = margin(r = 20), colour = "black"),
          axis.ticks.y = element_line(size = 1.5),
          axis.ticks.length = unit(0.3, "cm"),
          axis.line.y.right = element_blank(),
          axis.ticks.y.right = element_blank(), 
          axis.text.y.right = element_blank(), 
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line.x = element_line(size = 0.5, colour = "black"),
          axis.line.y = element_line(size = 0.5, colour = "black"),
          legend.position = "none",
          plot.margin = margin(1, 1, 1, 1),
          legend.spacing.x = unit(1, 'cm'))

```

# Analysis of sgRNA Log2FC for gene hits

```{r}

pick_alignment_type <- function(classification_data, alignment_type, stratification_data) {
  data <- read_csv(classification_data) %>%
    filter(alignment %in% alignment_type)
  
  return(data)
}

selected_guides <- c("perfect", "single mismatch", "pam-distal single mismatch", "pam-distal double mismatch", "multi-target guides", "non-targeting")

brunello_classification <- pick_alignment_type("../../data/sgrna_lfc_data/brunello_data/brunello_sgrna_alignment_classification.csv", selected_guides)
brunello_classification <- count_alignment_bin(brunello_classification, selected_guides)

brunello_library_and_lfc_data <- obtain_required_data("../../data/library_data/original_library/broadgpp-brunello-library-contents.tsv", 
                                                     "../../data/sgrna_lfc_data/output_normalized/brunello_a375_normalized_lfc.csv", 
                                                     brunello_classification[[1]])

# TODO: some sgRNA Log2FC data for Brunello is missing because of T0 filtering
brunello_original_only_hits_analysis <- brunello_original_only_hits_analysis %>%
  left_join(brunello_library_and_lfc_data, join_by("sgRNA")) %>%
  # drop sgrna with missing log2fc
  drop_na()







boxplot_lfc <- brunello_original_only_hits_analysis %>%
  ggboxplot(x = "is_depmap_essential", 
            y = "mean",
            outliers = FALSE) +
  labs(title = "", 
         x = "Gene hits", 
         y = "Averaged median sgRNA Log2FC") +
    theme(plot.margin = margin(10, 10, 25, 10),
          strip.text.x = element_text(size = 14),
          axis.text.y = element_text(size = 14, colour = "black"),
          axis.ticks.y = element_line(size = 1.5),
          axis.ticks.x = element_blank(), 
          axis.ticks.length = unit(0.1, "cm"),
          axis.title.x = element_blank(),
          axis.title.y = element_text(size = 14, vjust = 0.5, margin = margin(r = 20)),
          panel.grid.major = element_line(size = 0.5),
          panel.grid.minor = element_blank(),
          axis.line.x = element_line(size = 0.5),
          axis.line.y = element_line(size = 0.5), 
          line = element_line((size = 2), colour = 'black'),
          legend.position = "right",
          legend.text = element_text(size = 12)) +
  scale_x_discrete(labels = c("Gene hits identified as \nDepMap not essential (A375 cells)", "Gene hits identified as \nDepMap essential (A375 cells)"))

 # get stats
  
  b <- ggplot_build(boxplot_lfc)
  stats <- b$data[[1]]
  
  label_df <- stats %>%
    transmute(
      x = x,
      y = ymax + 0.2,          # add padding
      label = round(ymax, 2)   # or any custom label
    )
  
  count <- brunello_original_only_hits_analysis %>%
    select(is_depmap_essential) %>%
    count(is_depmap_essential)
  
  count <- count %>% bind_cols(stats %>% select(x, ymin))
  
  boxplot_lfc <-  boxplot_lfc +
                                geom_text(
                                  data = count,
                                  aes(x = x, y = ymin - 0.5, label = paste0("n = ", n)),
                                  angle = 45,
                                  vjust = 0,
                                  hjust = 0.5,
                                  size = 3.5
                                )
  
  boxplot_lfc



```























### Jacquere analysis

```{r}
jacquere_classification <- pick_alignment_type("../../data/sgrna_lfc_data/jacquere_data/jacquere_sgrna_alignment_classification.csv", selected_guides)
jacquere_classification <- count_alignment_bin(jacquere_classification, selected_guides)

depmap_common_essential <- read_csv("../../data/CRISPRInferredCommonEssentials.csv") %>%
  mutate(Essentials = str_remove(Essentials, "\\s*\\(.*\\)")) %>%
  pull(Essentials)

jacquere_essentiality_profiles <- jacquere_original_hits %>%
  select(Gene, Diff, hits_classification) %>%
  dplyr::rename("gene" = "Gene")

jacquere_original_only_hits_analysis <- jacquere_classification[[1]] %>%
  filter(gene %in% jacquere_original_only_hits) %>%
  left_join(jacquere_essentiality_profiles, join_by(gene)) %>%
  mutate(is_depmap_essential = ifelse(gene %in% depmap_common_essential, TRUE, FALSE))

not_essential_but_hits_jacquere <- jacquere_original_only_hits_analysis %>%
  select(-spacer) %>%
  filter(is_depmap_essential == FALSE)

survey <- jacquere_original_only_hits_analysis %>%
  select(gene, alignment, alignment_bin, Diff) %>%
  group_by(gene) %>%
  count(alignment, alignment_bin) %>%
  dplyr::rename("num_guides" = "n")  %>%
  mutate(is_depmap_essential = ifelse(gene %in% depmap_common_essential, TRUE, FALSE)) %>%
  ungroup(gene)

survey %>%
  select(gene, is_depmap_essential) %>%
  distinct() %>%
  count(is_depmap_essential) %>%
  dplyr::rename("num_genes" = "n") %>%
  ggplot(aes(is_depmap_essential, num_genes)) +
     geom_col(fill = "#1E88E5") +
     theme_minimal() +
     labs(x = "DepMap common essential genes", y = "Number of gene hits") +
     geom_text(aes(label = paste("n= ", num_genes, sep="")),
                nudge_y = 10,
                nudge_x = 0,
                size = 8) +
  theme(axis.text.x = element_text(size = 25, vjust = 0.7, colour = 'black'),
          axis.text.y = element_text(size = 25, colour = "black"),
          axis.title.x = element_text(size = 25, vjust = 0.5, margin = margin(t = 20), colour = "black"),
          axis.title.y = element_text(size = 25, vjust = 0.5, margin = margin(r = 20), colour = "black"),
          axis.ticks.y = element_line(size = 1.5),
          axis.ticks.length = unit(0.3, "cm"),
          axis.line.y.right = element_blank(),
          axis.ticks.y.right = element_blank(), 
          axis.text.y.right = element_blank(), 
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line.x = element_line(size = 0.5, colour = "black"),
          axis.line.y = element_line(size = 0.5, colour = "black"),
          legend.position = "none",
          plot.margin = margin(1, 1, 1, 1),
          legend.spacing.x = unit(1, 'cm'))
```









