---
title: "Survey original target genes in all libraries"
author: "Author: Stefanus Bernard"
date: "Date: `r format(Sys.time(), '%d %B %Y')`"
output: 
    html_document:
      theme: cerulean
      toc: true
      toc_float: true
      number_sections: true
      self_contained: true
---

```{r}
library(tidyverse)
library(envalysis)
library(HGNChelper)
source('~/CRISPR-KO-GuideRefine/GuideRefine_functions.R')
source("00_CRISPR-KO-library-survey-functions.R")
```

# Import all sgRNA library

```{r}

terms <- c("CONTROL", "Control", "control", "INTRON", "Intron", "intron", "LacZ", "luciferase", "NO_SITE", "ONE_INTERGENIC_SITE")
# lacZ and luciferase are the control in Toronto V3 library
terms_for_filtering <- paste(terms, collapse = "|")

avana <- import_sgrna_library("../data/library_data/avana_library.tsv", terms_for_filtering) %>% select(gene) %>% distinct() %>% pull(gene)
brunello <- import_sgrna_library("../data/library_data/broadgpp-brunello-library-contents.tsv", terms_for_filtering) %>% select(gene) %>% distinct() %>% pull(gene)
toronto <- import_sgrna_library("../data/library_data/tkov3_guide_sequence.tsv", terms_for_filtering) %>% select(gene) %>% distinct() %>% pull(gene)
yusa <- import_sgrna_library("../data/library_data/yusa_hcrispr_ko_grnas.tsv", terms_for_filtering) %>% select(gene) %>% distinct() %>% pull(gene)
jacquere <- import_sgrna_library("../data/library_data/Jacquere_PerGuideAnnotations_Quota4.tsv", terms_for_filtering) %>% select(gene) %>% distinct() %>% pull(gene)


standardize_gene_symbol <- function(list_gene) {
  df <- checkGeneSymbols(list_gene)
  standardized_gene <- df %>% mutate(Suggested.Symbol = if_else(is.na(Suggested.Symbol), x, Suggested.Symbol)) %>% pull(Suggested.Symbol)
  return(standardized_gene)
}

avana <- standardize_gene_symbol(avana)
brunello <- standardize_gene_symbol(brunello)
toronto <- standardize_gene_symbol(toronto)
yusa <- standardize_gene_symbol(yusa)
jacquere <- standardize_gene_symbol(jacquere)

```

# Import HGNC dataset

```{r}
dataset_hgnc <- "https://storage.googleapis.com/public-download-files/hgnc/tsv/tsv/hgnc_complete_set.txt"
# to match with paralog investigation later, we obtained protein-coding genes defined by HGNC with established ENSEMBL Gene ID
hgnc <- read_tsv(dataset_hgnc)
  # filter(locus_group == "protein-coding gene" & !is.na(ensembl_gene_id)) %>%
  # select(symbol, locus_group, ensembl_gene_id)

hgnc_avana <- hgnc %>% filter(symbol %in% avana) %>% select(symbol, locus_group, locus_type) %>% mutate(library = "avana")
hgnc_brunello <- hgnc %>% filter(symbol %in% brunello) %>% select(symbol, locus_group, locus_type) %>% mutate(library = "brunello")
hgnc_toronto <- hgnc %>% filter(symbol %in% toronto) %>% select(symbol, locus_group, locus_type) %>% mutate(library = "tkov3")
hgnc_yusa <- hgnc %>% filter(symbol %in% yusa) %>% select(symbol, locus_group, locus_type) %>% mutate(library = "yusa")
hgnc_jacquere <- hgnc %>% filter(symbol %in% jacquere) %>% select(symbol, locus_group, locus_type) %>% mutate(library = "jacquere")

all_genes <- rbind(hgnc_avana, hgnc_brunello, hgnc_toronto, hgnc_yusa, hgnc_jacquere)


```


















