---
title: "Analysis of multi-target and off-target sgRNAs across libraries"
author: "Author: Stefanus Bernard"
date: "Date: `r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document :
    theme : cerulean
    toc : true
    toc_float : true
    number_section : true
---

```{r setup, include=FALSE}
library(tidyverse)
library(VennDiagram)
library(ggvenn)
library(ggbreak)
library(xlsx)

source('~/CRISPR-KO-GuideRefine/GuideRefine_functions.R')
source("./00_CRISPR-KO-library-survey-functions.R")
```

# Import data containing removed genes from each library

```{r}

removed_genes <- read_csv("../data/biogrid_crispr_ko_data/important_data/removed_genes_all_library.csv")

```

# Prepare data from BIOGRID

```{r}

biogrid_index <- read_tsv("../data/biogrid_crispr_ko_data/important_data/BIOGRID-ORCS-SCREEN_INDEX-2.0.18.index.tab.txt")

# we select CRISPR KO screen based on cell proliferation, library type is CRISPR knockout (CRISPRn), and containing list of full genes and their hits (full size available - yes)

# available library total:  37
# selected library:
# 1. Avana
# 2. Brunello (human)
# 3. Toronto Knockout version 3 (TKOv3)
# 4. None for Project Score

# create blank dataframe
df_avana_screen <- data.frame()

avana_screen_studies <- biogrid_index %>%
  filter(PHENOTYPE == "cell proliferation" & LIBRARY_TYPE == "CRISPRn" & FULL_SIZE_AVAILABLE == "Yes") %>%
  # count(AUTHOR) %>%
  # dplyr::rename("number_of_screens" = "n")
  pull(`#SCREEN_ID`)

for (screen_id in avana_screen_studies) {
  data = read_tsv(paste("../data/biogrid_crispr_ko_data/BIOGRID-ORCS-SCREEN_", screen_id, "-2.0.18.screen.tab.txt", sep = ""), col_names = FALSE, skip = 1)
  
  # X13 is column indicating whether the genes is the hits or not
  data <- data %>% filter(X13 == "YES")
  df_avana_screen = rbind(df_avana_screen, data)
}

colnames(df_avana_screen) <- c("SCREEN_ID", "IDENTIFIER_ID", "IDENTIFIER_TYPE", "OFFICIAL_SYMBOL", "ALIASES", "ORGANISM_ID", "ORGANISM_OFFICIAL", "SCORE.1", "SCORE.2", "SCORE.3", "SCORE.4", "SCORE.5", "HIT", "SOURCE")

```

# Check if the removed genes is in the CRISPR screen data

```{r}

removed_genes_not_hits <- setdiff(unique(removed_genes$avana_removed_genes_all), unique(df_avana_screen$OFFICIAL_SYMBOL))

removed_genes_hits <- df_avana_screen %>% 
  filter(OFFICIAL_SYMBOL %in% removed_genes$avana_removed_genes_all) %>%
  count(OFFICIAL_SYMBOL) %>%
  dplyr::rename("count_appear_in_screen" = "n") %>%
  count(count_appear_in_screen) %>%
  dplyr::rename("num_genes" = "n") %>%
  add_row(count_appear_in_screen = 0, num_genes = length(removed_genes_not_hits)) %>%
  arrange(count_appear_in_screen)

breaks <- c(-Inf, 0, 50, 100, 150, 200, 250, 300, Inf)
labels <- c("0", "1–50", "50–100", "100–150", "150–200", "200–250", "250–300", ">300")
  
removed_genes_hits$appearance_bin <- cut(removed_genes_hits$count_appear_in_screen,
                                        breaks = breaks,
                                        labels = labels,
                                        right = TRUE)

removed_gene_hits_bin <- removed_genes_hits %>%
  select(num_genes, appearance_bin) %>%
  group_by(appearance_bin) %>%
  summarise(num_genes_total = sum(num_genes))


```



```{r}
removed_genes_list_hits <- df_avana_screen %>% 
  filter(OFFICIAL_SYMBOL %in% removed_genes$avana_removed_genes_all) %>%
  group_by(OFFICIAL_SYMBOL) %>%
  count(OFFICIAL_SYMBOL) %>%
  dplyr::rename("count_as_hits" = "n") %>%
  ungroup()



import_report_without_control <- function(file_dir, control_terms) {
  
  data <- read_excel(paste(file_dir))
  data <- data %>% filter(!str_detect(gene, terms_for_filtering))
  return(data)
  
}

avana <- 'avana_library'

terms <- c("CONTROL", "Control", "control", "INTRON", "Intron", "intron", "LacZ", "luciferase")
# lacZ and luciferase are the control in Toronto V3 library

terms_for_filtering <- paste(terms, collapse = "|")

avana_report <- import_report_without_control(paste('~/CRISPR-KO-GuideRefine/output_cleaning/T2T-CHM13/', avana, '_full_report.xlsx', sep = ''))

query_hits <- removed_genes_list_hits %>% filter(count_as_hits == 344) %>% pull(OFFICIAL_SYMBOL)

avana_report_query_hits <- avana_report %>% filter(gene %in% query_hits)

```



