---
title: "Analysis of multi-target and off-target sgRNAs across libraries"
author: "Author: Stefanus Bernard"
date: "Date: `r format(Sys.time(), '%d %B %Y')`"
output:
  html_document :
    theme : cerulean
    toc : true
    toc_float : true
    number_section : true
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggbreak)
library(clinfun)
library(ggsignif)
library(ggpubr)
library(rstatix)
library(effsize)
library(dplyr)

source('../../GuideRefine/GuideRefine_functions.R')
source("./00_CRISPR-KO-library-survey-functions.R")
```

# Load data (once)

```{r load-classification}

avana_raw    <- read_csv("../data/sgrna_lfc_data/avana_data/avana_sgrna_alignment_classification_T2T.csv")
tkov3_raw    <- read_csv("../data/sgrna_lfc_data/tkov3_data/tkov3_sgrna_alignment_classification_T2T.csv")
yusa_raw     <- read_csv("../data/sgrna_lfc_data/yusa_data/yusa_sgrna_alignment_classification_T2T.csv")
brunello_raw <- read_csv("../data/sgrna_lfc_data/brunello_data/brunello_sgrna_alignment_classification_T2T.csv")
jacquere_raw <- read_csv("../data/sgrna_lfc_data/jacquere_data/jacquere_sgrna_alignment_classification_T2T.csv")

```

```{r load-library-lfc}

avana_lfc_raw    <- load_library_lfc_raw("../data/library_data/original_library/avana_library.tsv",
                                          "../data/sgrna_lfc_data/output_normalized/avana_normalized_lfc.csv")

tkov3_lfc_raw    <- load_library_lfc_raw("../data/library_data/original_library/tkov3_guide_sequence.tsv",
                                          "../data/sgrna_lfc_data/output_normalized/tkov3_rpe1_normalized_lfc.csv")

yusa_lfc_raw     <- load_library_lfc_raw("../data/library_data/original_library/yusa_hcrispr_ko_grnas.tsv",
                                          "../data/sgrna_lfc_data/output_normalized/yusa_normalized_lfc.csv")

brunello_lfc_raw <- load_library_lfc_raw("../data/library_data/original_library/broadgpp-brunello-library-contents.tsv",
                                          "../data/sgrna_lfc_data/output_normalized/brunello_a375_normalized_lfc.csv")

# Jacquere sgRNA Log2FC data only available for ~60,000 sgRNAs
jacquere_lfc_raw <- load_library_lfc_raw("../data/library_data/original_library/Jacquere_PerGuideAnnotations_Quota4.tsv",
                                          "../data/sgrna_lfc_data/output_normalized/jacquere_normalized_lfc.csv")

```

# Multi-target sgRNA analysis — Fig2C, SuppFig2A–E

```{r multi-target-stratify}
source("./00_CRISPR-KO-library-survey-functions.R")

multi_guides <- c("perfect", "multi-target guides")

avana_multi    <- count_alignment_bin(filter(avana_raw,    alignment %in% multi_guides), multi_guides)
tkov3_multi    <- count_alignment_bin(filter(tkov3_raw,    alignment %in% multi_guides), multi_guides)
yusa_multi     <- count_alignment_bin(filter(yusa_raw,     alignment %in% multi_guides), multi_guides)
brunello_multi <- count_alignment_bin(filter(brunello_raw, alignment %in% multi_guides), multi_guides)
jacquere_multi <- count_alignment_bin(filter(jacquere_raw, alignment %in% multi_guides), multi_guides)

avana_lfc_multi    <- apply_stratification(avana_lfc_raw,    avana_multi[[1]])    %>% mutate(library = "avana")      %>% drop_na()
tkov3_lfc_multi    <- apply_stratification(tkov3_lfc_raw,    tkov3_multi[[1]])    %>% mutate(library = "toronto_v3") %>% drop_na()
yusa_lfc_multi     <- apply_stratification(yusa_lfc_raw,     yusa_multi[[1]])     %>% mutate(library = "yusa")       %>% drop_na()
brunello_lfc_multi <- apply_stratification(brunello_lfc_raw, brunello_multi[[1]]) %>% mutate(library = "brunello")   %>% drop_na()
jacquere_lfc_multi <- apply_stratification(jacquere_lfc_raw, jacquere_multi[[1]]) %>% mutate(library = "jacquere")  %>% drop_na()

combined_multi <- rbind(avana_lfc_multi, tkov3_lfc_multi, yusa_lfc_multi, brunello_lfc_multi, jacquere_lfc_multi) %>%
  mutate(
    library   = factor(library,   levels = c("brunello", "toronto_v3", "yusa", "avana", "jacquere")),
    alignment = factor(alignment, levels = multi_guides)
  )

```

```{r multi-target-export}

visualize_two_group(combined_multi,
                    "../figure/Fig02_analysis_off-target-sgrna/Fig2C_combined_library_multi_target.png")

visualize_stratify_alignment(brunello_lfc_multi, "number of perfect on-target alignment", "../figure/Fig02_analysis_off-target-sgrna/SuppFig2A_brunello_multi_target.png")
visualize_stratify_alignment(tkov3_lfc_multi,    "number of perfect on-target alignment", "../figure/Fig02_analysis_off-target-sgrna/SuppFig2B_tkov3_multi_target.png")
visualize_stratify_alignment(yusa_lfc_multi,     "number of perfect on-target alignment", "../figure/Fig02_analysis_off-target-sgrna/SuppFig2C_yusa_multi_target.png")
visualize_stratify_alignment(avana_lfc_multi,    "number of perfect on-target alignment", "../figure/Fig02_analysis_off-target-sgrna/SuppFig2D_avana_multi_target.png")
visualize_stratify_alignment(jacquere_lfc_multi, "number of perfect on-target alignment", "../figure/Fig02_analysis_off-target-sgrna/SuppFig2E_jacquere_multi_target.png")

```

# Single mismatch sgRNA analysis — Fig2D, SuppFig2F–J

```{r single-mismatch-stratify}
source("./00_CRISPR-KO-library-survey-functions.R")

single_guides <- c("perfect", "single mismatch")

avana_single    <- count_alignment_bin(filter(avana_raw,    alignment %in% single_guides), single_guides)
tkov3_single    <- count_alignment_bin(filter(tkov3_raw,    alignment %in% single_guides), single_guides)
yusa_single     <- count_alignment_bin(filter(yusa_raw,     alignment %in% single_guides), single_guides)
brunello_single <- count_alignment_bin(filter(brunello_raw, alignment %in% single_guides), single_guides)
jacquere_single <- count_alignment_bin(filter(jacquere_raw, alignment %in% single_guides), single_guides)

avana_lfc_single    <- apply_stratification(avana_lfc_raw,    avana_single[[1]])    %>% mutate(library = "avana")      %>% drop_na()
tkov3_lfc_single    <- apply_stratification(tkov3_lfc_raw,    tkov3_single[[1]])    %>% mutate(library = "toronto_v3") %>% drop_na()
yusa_lfc_single     <- apply_stratification(yusa_lfc_raw,     yusa_single[[1]])     %>% mutate(library = "yusa")       %>% drop_na()
brunello_lfc_single <- apply_stratification(brunello_lfc_raw, brunello_single[[1]]) %>% mutate(library = "brunello")   %>% drop_na()
jacquere_lfc_single <- apply_stratification(jacquere_lfc_raw, jacquere_single[[1]]) %>% mutate(library = "jacquere")  %>% drop_na()

combined_single <- rbind(avana_lfc_single, tkov3_lfc_single, yusa_lfc_single, brunello_lfc_single, jacquere_lfc_single) %>%
  mutate(
    library   = factor(library,   levels = c("brunello", "toronto_v3", "yusa", "avana", "jacquere")),
    alignment = factor(alignment, levels = single_guides)
  )

```

```{r single-mismatch-export}

visualize_two_group(combined_single,
                    "../figure/Fig02_analysis_off-target-sgrna/Fig2D_combined_library_single_mismatch.png",
                    comparison_group = "single mismatch",
                    comparison_label = "Single mismatch")

visualize_stratify_alignment(brunello_lfc_single, "number of single mismatch \noff-target alignment", "../figure/Fig02_analysis_off-target-sgrna/SuppFig2F_brunello_single_mismatch.png")
visualize_stratify_alignment(yusa_lfc_single,     "number of single mismatch \noff-target alignment", "../figure/Fig02_analysis_off-target-sgrna/SuppFig2G_yusa_single_mismatch.png")
visualize_stratify_alignment(tkov3_lfc_single,    "number of single mismatch \noff-target alignment", "../figure/Fig02_analysis_off-target-sgrna/SuppFig2H_tkov3_single_mismatch.png")
visualize_stratify_alignment(avana_lfc_single,    "number of single mismatch \noff-target alignment", "../figure/Fig02_analysis_off-target-sgrna/SuppFig2I_avana_single_mismatch.png")
visualize_stratify_alignment(jacquere_lfc_single, "number of single mismatch \noff-target alignment", "../figure/Fig02_analysis_off-target-sgrna/SuppFig2J_jacquere_single_mismatch.png")

```

# Effect size (Cliff's delta)

```{r effect-size}

calculate_wilcoxon_cles(jacquere_lfc_multi,  "multi-target guides", "perfect")
calculate_wilcoxon_cles(jacquere_lfc_single, "single mismatch",     "perfect")

```
